// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.22.0
// source: my_proto_stuff.proto

package my_proto_stuff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyProtoStuff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 string `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 int32  `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
}

func (x *MyProtoStuff) Reset() {
	*x = MyProtoStuff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_proto_stuff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyProtoStuff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyProtoStuff) ProtoMessage() {}

func (x *MyProtoStuff) ProtoReflect() protoreflect.Message {
	mi := &file_my_proto_stuff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyProtoStuff.ProtoReflect.Descriptor instead.
func (*MyProtoStuff) Descriptor() ([]byte, []int) {
	return file_my_proto_stuff_proto_rawDescGZIP(), []int{0}
}

func (x *MyProtoStuff) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

func (x *MyProtoStuff) GetField2() int32 {
	if x != nil {
		return x.Field2
	}
	return 0
}

type ProtoWithOneof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopField string `protobuf:"bytes,1,opt,name=top_field,json=topField,proto3" json:"top_field,omitempty"`
	// Types that are assignable to TestOneof:
	//
	//	*ProtoWithOneof_Field1
	//	*ProtoWithOneof_Field2
	TestOneof isProtoWithOneof_TestOneof `protobuf_oneof:"test_oneof"`
}

func (x *ProtoWithOneof) Reset() {
	*x = ProtoWithOneof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_proto_stuff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoWithOneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoWithOneof) ProtoMessage() {}

func (x *ProtoWithOneof) ProtoReflect() protoreflect.Message {
	mi := &file_my_proto_stuff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoWithOneof.ProtoReflect.Descriptor instead.
func (*ProtoWithOneof) Descriptor() ([]byte, []int) {
	return file_my_proto_stuff_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoWithOneof) GetTopField() string {
	if x != nil {
		return x.TopField
	}
	return ""
}

func (m *ProtoWithOneof) GetTestOneof() isProtoWithOneof_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (x *ProtoWithOneof) GetField1() string {
	if x, ok := x.GetTestOneof().(*ProtoWithOneof_Field1); ok {
		return x.Field1
	}
	return ""
}

func (x *ProtoWithOneof) GetField2() int32 {
	if x, ok := x.GetTestOneof().(*ProtoWithOneof_Field2); ok {
		return x.Field2
	}
	return 0
}

type isProtoWithOneof_TestOneof interface {
	isProtoWithOneof_TestOneof()
}

type ProtoWithOneof_Field1 struct {
	Field1 string `protobuf:"bytes,2,opt,name=field1,proto3,oneof"`
}

type ProtoWithOneof_Field2 struct {
	Field2 int32 `protobuf:"varint,3,opt,name=field2,proto3,oneof"`
}

func (*ProtoWithOneof_Field1) isProtoWithOneof_TestOneof() {}

func (*ProtoWithOneof_Field2) isProtoWithOneof_TestOneof() {}

var File_my_proto_stuff_proto protoreflect.FileDescriptor

var file_my_proto_stuff_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x74, 0x75, 0x66, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x73, 0x74, 0x75, 0x66, 0x66, 0x22, 0x3e, 0x0a, 0x0c, 0x4d, 0x79, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x53, 0x74, 0x75, 0x66, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x22, 0x6f, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x57,
	0x69, 0x74, 0x68, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x70,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12,
	0x18, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x42, 0x0c, 0x0a, 0x0a, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x75, 0x62, 0x65, 0x72, 0x61, 0x74, 0x2d, 0x67, 0x6f,
	0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x74, 0x75, 0x66, 0x66, 0x2f, 0x6d, 0x79, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x74, 0x75, 0x66, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_my_proto_stuff_proto_rawDescOnce sync.Once
	file_my_proto_stuff_proto_rawDescData = file_my_proto_stuff_proto_rawDesc
)

func file_my_proto_stuff_proto_rawDescGZIP() []byte {
	file_my_proto_stuff_proto_rawDescOnce.Do(func() {
		file_my_proto_stuff_proto_rawDescData = protoimpl.X.CompressGZIP(file_my_proto_stuff_proto_rawDescData)
	})
	return file_my_proto_stuff_proto_rawDescData
}

var file_my_proto_stuff_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_my_proto_stuff_proto_goTypes = []interface{}{
	(*MyProtoStuff)(nil),   // 0: my_proto_stuff.MyProtoStuff
	(*ProtoWithOneof)(nil), // 1: my_proto_stuff.ProtoWithOneof
}
var file_my_proto_stuff_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_my_proto_stuff_proto_init() }
func file_my_proto_stuff_proto_init() {
	if File_my_proto_stuff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_my_proto_stuff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyProtoStuff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_my_proto_stuff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoWithOneof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_my_proto_stuff_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ProtoWithOneof_Field1)(nil),
		(*ProtoWithOneof_Field2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_my_proto_stuff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_my_proto_stuff_proto_goTypes,
		DependencyIndexes: file_my_proto_stuff_proto_depIdxs,
		MessageInfos:      file_my_proto_stuff_proto_msgTypes,
	}.Build()
	File_my_proto_stuff_proto = out.File
	file_my_proto_stuff_proto_rawDesc = nil
	file_my_proto_stuff_proto_goTypes = nil
	file_my_proto_stuff_proto_depIdxs = nil
}
